import tweepy
import pandas as pd
import os
import datetime

CONSUMER_KEY = "UdknJELvDORf0zuO6ir79em3r"
CONSUMER_SECRET = "MMFsntEXqGBxMmhAyNO7GnhdKu63uOcCMc0OmeuJrfrMp6fcfo"
ACCESS_TOKEN = "1162981636494905344-hII6sZwJFEuUHVlDV9NZEC6mPa3NMx"
ACCESS_TOKEN_SECRET = "aCQYth4FWI1Iua9iyl1doRUIP5dDCYMHRR68KR6aiY1sA"

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth, wait_on_rate_limit=True)

user_list = {
    'hashimoto_lo',
    'dpfp_shimane',
    'kagawasanuki1',
    'IwasakiIwamo',
    'itsukihiguma',
    'oyaji1990',
    'yoheiogawa_DPFP',
    'Henry66239746',
    'hatocotoco',
    'shimago1976',
    'tomoekakuda',
    'michiru10139',
    'umetsuyosei',
    'dpfp_shiga',
    'oda_dpfp',
    'MintoJPN',
    'shikichan_1106',
    'kokumin_fukuoka',
    'tamakiyuichiro',
    'UmQ7ZkNooT9Tzil',
    'mirailabo0913',
    'tomiyama_ka',
    'ishiguronerima',
    'hsmdaiki',
    'fukasakuyui',
    'KikuchiDaijiro',
    'yumibetterworld',
    'takazawa1',
    'kokumin_Ouen_hs',
    'kokuminhodo',
    'Rabbit_Uphill',
    'mariko_hichiwa',
    'wako0501',
    'jtak_95',
    'Yhy0f2csL0LE2hv',
    'estakihabu',
    'OsakaKiriManabu',
    'quartetnight78',
    'KokuUsa_bot',
    'oN8fY85PBETyut1',
    'gokokuminymgt',
    'minminminmin703',
    'Doll0takuma3',
    '3Obtb',
    'nkm27',
    'dmitrykuratako1',
    'YamaneYohei',
    'kinno_takayasu',
    'Asklily10498',
    'suzukiatsushi_',
    'KamadaYasuharu',
    'okmachioka',
    'maekawa190',
    'proton15733813',
    'lpSaWpiOJwz6uqd',
    'DZ513fTtYo2Yphm',
    'shyonchi',
    'kumamimami1',
    'pinopino_8880',
    'Takayasuhiro329',
    'mamitamuratw',
    'tmk0fficial',
    'tkb_riho',
    'ikenaga1987',
    'keik198',
    'Kisuzu_udon',
    'KHagi_Funabashi',
    'yama0117',
    'miyahara_hiro',
    'nadeshiko1000',
    'DPFPnews',
    'takunari_ishida',
    'mikisanuki2023',
    'jeftoshi1873',
    'atsuko_call',
    'Asano__Satoshi',
    'TachibanaMoi',
    'hirohitomatuok1',
    'kai_wkwk',
    'Miyagi_Suen',
    'sin2nissi',
    'h_ishizaki',
    'satoushio14',
    'kyoko_ohta',
    'g_KEN0428',
    'eijih1102',
    'kokumin_ngsk',
    'kokumindata',
    'maeda_kokumin',
    'kaori_kokumin',
    'HyoGen1980',
    'dpfptokyo',
    'ibarakiusagi',
    'Ishida_shingo51',
    'rurukisakamoto',
    'hanako_onuki',
    'rabizipangse7',
    'kuro13515865',
    'KokuminHokkaido',
    'HamaMako0518',
    'kagawakokumin',
    'fxI8dS0hrIw6lyl',
    'Shiro117385631',
    'utoka_da4',
    'RisingOmukaiSun',
    'Sami13003868',
    'FukasakuKj',
    'suzuki_yuma1009',
    'Moi_Jacqueline_',
    'jbi_fd',
    'totugeki360',
    'fbtgKr7qya4wbnH',
    'Kokumin_Kobuta',
    'TokizakiNaoyuki',
    '1209ijhshenp',
    'Aya_LSSAH',
    'itsumo_nemui26',
    'Lizhitiger',
    'otsukisama505',
    'kokumin_kurabu',
    'mourimii',
    'Siele111',
    'buraiburai417',
    'No8Real',
    'KeeweeSan',
    'kouchi_rabbit',
    'Andy_seizi',
    'masaru_03010',
    'shinju_nakayama',
    'tako_ne_kokumin',
    'cAnon_selicA',
    'itotakae0630',
    'corerisufire55',
    'atm_09_st_rsc',
    'shirock_',
    'yattodeta',
    'miso_GP',
    'JLDP87',
    'tsujiakihiko',
    'toraland8473',
    'Akazawa8810',
    'yuuko_i10',
    'kiyo_mayuzumi',
    'minoko_boyaki',
    'horu8888',
    'que_yan16',
    'lovieve_',
    'smith796000',
    'YUKIusagai',
    'GGkh2x',
    'hyakukei',
    'do_pl_fi_pr',
    'TwilightAvenue_',
    'spirvtus_67',
    'madamshiwori',
    'der_Schurke13',
    'kimunny',
    'N_28G',
    'watchieee1',
    'japancom1945',
    'sora987654321s',
    'katsura_403',
    'hayo_mama',
    'chiiki_saisei',
    'watanishi459',
    'businofuziwara',
    '1lovewater',
    'CoKumakuma',
    'AKIRAMANABE0125',
    'tadatakah',
    'tabatasiseifri1',
    'udonken_jeiu',
    'k8ukVD51mxskQHW',
    'Chijisen',
    'kobayanmoomin',
    'jun36294488',
    'musasabi_town',
    'taisuke_nkmr',
    'pWyaf5dJOmW3043',
    'diob34',
    'New__wind',
    'minato29110131',
    'Sappololugger',
    'aPIuqW0MKeXqbqJ',
    'VenusBBA3Trees',
    'amnu_sj',
    'UDON203',
    'keisukekamada01',
    'YumiYamaki107',
    'YoichiTakahashi',
    'MseraOfficial',
    'ShioriYamao',
    'kurarin0116',
    'TK_Mitsuhashi',
    'SF_SatoshiFujii',
    'Iumo13',
    'namistof_JP031',
    'nagatomoshinji',
    'hamanoyoshifumi',
    'TWNapoli',
    'satoushio40',
    'kawakam38686763',
    'ouchi_kazuya',
    'ReiEnomoto',
    'kokumin_chiba',
    'shimazutetsuya6',
    'okuda_shinichi',
    'kuroda__taro',
    'kagaoshimaa',
    'gekiatsu15000',
    '6CZAUD5eBStXhBt',
    'K66798019',
    'TO_huka_617',
    'KPresident50',
    'azuma19981209',
    'Keisuke_Hamazoe',
    'kesutora2010',
    'PINRO1312',
    'BeAkashi',
    'Toru_Fukuta',
    'sdfpnn',
    'santa_akashiya',
    'kurumarudogu',
    'ririichijyo',
    'antitaxhike',
    'kyomkyom01',
    '9IoMoUZiR9LJMk8',
    'GuoZtev',
    'THek293',
    'qpFZ9lJu8POMdNF',
    'rolling_dice__',
    'ponpon1234565',
    'mimikaki000',
    'dokkoi_syaminto',
    'takuminorinn',
    '1124Hanada',
    'llN8QDTfchnaoBZ',
    'daisuke_giin',
    'nakahi',
    'chietoeru',
    'nohohon_peace',
    'kenitani',
    'masamasa7388',
    'oyasaininzinmar',
    'HATA_HARE',
    'minto_otnimX',
    'DxaZY4D7sQAA2BD',
    '6gGlHM58W5uuFZH',
    'umeda0000yuya',
    'gen_seishun',
    'Gveeenus',
    'neko_k56',
    'fire456789012',
    'edefefe2800',
    'reo_kobayashi07',
    'reiko_mtsmt',
    'chikuwaclinic',
    'KokuminArtclub',
    'daimonhakase',
    'YamadaH0',
    'mackenG222',
    'eichan0228',
    'takamasah',
    'R42089742',
    'simarisu114',
    'Westminster174',
    'higojyunketsu',
    'jackson07305101',
    'syrup_3756',
    'erhi20221005',
    '13CQd',
    'study20220203',
    'taaimonai365',
    'tamaki_no_oheya',
    'kokumin_minsyu',
    'korokorodanngo',
    'SUZUKInimienai',
    'qpxq5m4',
    'W3b7WIdm7ZYXphY',
    'kokumin2020911',
    'shimano_usagi',
    'tokyo_stew',
    'TS57243093',
    'LMiJV7Ry1URhYNL',
    'nNjSzXviqDblT1J',
    'kokumintaro',
    'sam36578382',
    'kabutotomoni',
    '107sanuki',
    'ohtake0815',
    'hamadahiroki',
    'tassy0123',
    'kagawarsa',
    'Yamato_ozchn',
    'GVPOl3Dmf59NYZQ',
    'sakuomama',
    '6xPn0Lm5oevlHhC',
    'usaginomimirin',
    'min23wings',
    'QLVT01B3fzLumju',
    'chugatanoinu',
    'garyo_koumei02',
    'minmin_word',
    'kokumin_kuma',
    'osunishiokades',
    'sudakazuyuki',
    'mami_formychild',
    'tomoyan_yoko',
    'kokuminminshu',
    'Kawakita_Masaru',
    'U12ISHd1e73D9jg',
    'Ti_DPFP',
    'MiyukiMatuda',
    'KokuminLiqour',
    'ksk_0910',
    'ya3eduvm',
    'kumataparty',
    'akinobu593',
    'jin101082_altoe',
    '1125tamachan',
    'karuishi_y',
    'mineuchi_maru',
    'yukinumatautazu',
    'Date_Uradayo',
    'xstHLFBKcyHW7Wv',
    'rrr_kopp',
    'gifudpfp',
    'yuu_kokumin',
    'inzai_mariko',
    'xcoY2ekfcg5n4JL',
    'KokuminKokkai',
    'Darklord_616',
    'WsG72prM3pzJGQc',
    'inaba3042',
    'tannomidori',
    '21__marimo',
    'kanetou55',
    'yukarikanetou',
    'TamakiBot_',
    'yu_kokukoku',
    'kokumin_myzk',
    'bocchansl',
    'yatt_yatt_yatt',
    'Kokumin_setuka',
    'hide_usuki',
    'ks_kunkun',
    'milman_milmil',
    '_nana59_',
    'denki_osaka',
    'maetsuyoshi',
    'earthteikoku',
    'kokumin_tks',
    'MICHIEIMAI',
    'iine_shimashita',
    'shinjiiwasaki2',
    'hayato072217',
    'dpfpmiyazaki1',
    'oneginosato',
    'bottomless496',
    'kokumin_hamano',
    'CxWGIphf76QNnmh',
    'kajiwarahideki',
    'min_min_1971',
    'Yamatake914',
    'shibarakuhonne',
    'kokumin_fukui',
    'Rlj6HQi9WBzrbYG',
    'hHvXuAU0jHwOz4v',
    'blue_kokumin',
    'minminsagi',
    'usagilioninu',
    'zezehihigo',
    'kokuminyou',
    'YAMA0876',
    'fune1852',
    'CHAGEYAMA1',
    'one_ehime',
    'watanabehiro11',
    'motoyama1982',
    'koizumimiyuki',
    'okarintaro',
    'Lrh0AIbYaUPglNO',
    'Northern_Land_V',
    'sion01687281',
    'kenshinkokumin',
    'denki_kanagawa',
    'save_hiroshima',
    'inabatohoku',
    'tomooooon1121',
    'ankunankun',
    'YuduMarins_DPFP',
    '1V3jWtGD6r7cE5L',
    'hiro914',
    'jb7og1lr24',
    'ootani_staff',
    'wasabihumi',
    'taitei891',
    'nananannna0',
    'SEIJI1333',
    'yasuki_kanoh',
    'shun_1UP',
    'washo35221204',
    '54yellowrabbit',
    'Pinkbloodcorgie',
    'inchos_dpfp',
    'Kochi_007',
    'DSPJ1997',
    'kagaya_yagaka',
    'sakurazaka_herj',
    'P8qARon3FgTpwjL',
    'sd_t2w',
    'tokita812',
    'kitahara_yuji',
    '8no_no_no8',
    'hasegawa_takako',
    'koji_oashi',
    'f7SYmFBYMivVBCE',
    'mike_kza53',
    'okitsutokyo',
    'nozomi_ngsk',
    'rzjxRHv2Z81bTfM',
    'Lightning2014',
    'kenbo_yamagata',
    'akanemaru0120',
    'hideo_ito',
    'tamiyukikihara',
    'ShiraisiA',
    'usagi_05jp',
    'Seijiaka1',
    'kokumin_koho',
    'milkkkkkkkkkke1',
    'kazkiku50',
    'nomuramiho3434',
    'TJK07370425',
    'SHIN7579',
    'xxD6A8hdiAQpLkL',
    'ZJ85aGrqQYBMA0Z',
    'KENSEIKAI_KOHO',
    'Youthminmin2020',
    'fW5PCPkl9KoquLV',
    'heikawomamoru',
    'nekomo9',
    'lMoTvYeA',
    'kanitoudonsuki',
    'doudeshogottan',
    'puffing_tom4',
    'Cassius_WK46',
    'RL_tita',
    'hiro_0202aq',
    'nariri_nariri',
    'T_KAWAI_SANGIIN',
    'TAKURI_suzuki03',
    'WalkStart',
    'yushi51919',
    'matsuseikei21',
    'almondlovekeiba',
    'banzaiJAPONICA',
    'akirakokumin',
    'ecorin_g',
    'youthdpfp',
    '__sckm',
    'dpfp_new_idea',
    'RYUwWda4Adp5iB0',
    'minshinhachioji',
    'gyokyuukai',
    'SHIMBA_OFFICE',
    'inausa1996',
    'horianiki',
    'YurikoOtani',
    'DxjvnI',
    'turaturataro',
    'manabu_moq',
    'manattiman',
    'katti_2464',
    'ZooSWarthe',
    'jinseisaik',
    'toarusyakai',
    'gawagawa56',
    'ka_tyanday',
    'DeltaCat9',
    'glicoro',
    'artheid3',
    'norinakama_papa',
    'ISSAJAPAN815',
    'y9Hht0Wgq4KSrCC',
    'Tae_Amano',
    'HirokoToshimaku',
    'kadayukiko',
    'kokumin_osaka',
    'Uematsu1987',
    'narita_yusuke',
    '8TZHmAza0WE2fQm',
    'vavavalloon',
    'PWOERtoJAPAN',
    'gogo_yatawaka',
    'shin_sk0901',
    'kokumin_kng',
    'KatahiroY',
    'IsozakiTetsuji',
    'PinkFlamingos69',
    'Takezume_H',
    'midopin',
    'dodododokadoka',
    'hirox246',
    'DPFP_DietInfo',
    'harada_tsm22',
    'yoshinomasato',
    'osawanoboru',
    'SekiguchiTaichi',
    'okatakashi_oota',
    'shiraiwa_net',
    'maru_ko_enkai',
    'marboyanbo',
    'NorihiroUehata',
    'shuheikishimoto',
    'shinya8484',
    'satoyasuki7',
    'mihojimukyoku',
    'chimbeyoshihiro',
    'juntarotakeuchi',
    'YamazakiMaya',
    'akimitsukurogi',
    'kokuminibaraki',
    'newkokuminnara',
    'kokumin_ymgc',
    'kokumin_aichi_',
    'FeFQFsgref5wS6U',
    'hagamichiya',
    'kennichisakurai',
    'Saitou_424',
    'hide_futakawa',
    'mayumi_ogawa',
    'ELkDWoHH4sVMMD9',
    'ochitatsuya0711',
    'ImlILWLwgsC8Ufk',
    'tomohisa_tanaka',
    'hiroyukishiman1',
    'motoshimorii',
    'nakataniayano',
    'Hashimoto_Mkhk',
    'y_ishiwatari',
    'Sukegawa_satoru',
    'IwataHirotaka',
    'kanetououentai',
    'bunkyotaizo',
    'NiheiFumitaka',
    'ryoma_mino',
    'satoakio310',
    'G1i9olE3i1NIWsA',
    'BVd5wh9e90eA5mj',
    'junko_okano',
    'minshin_y',
    'dpj_kagoshima',
    't_kakuda',
    'gutsdego',
    'kawai_akinari',
    'yamanoitakashi',
    'enoayu_minato',
    '_tanakaerika_',
    'KokuminOita',
    'kokumin_mie',
    'dp_tochigi',
    'minshuwakayama',
    'hamaoka_hiroki',
    'tarui_yoshikazu',
    'KzAGu2ES5XwFYUI',
    'yasuhirokogayu',
    'suzukimiyuki701',
    'madokayoriko',
    'yosshisuzuki',
    'katsuhikoasano',
    'Maehara2016',
    'kouhei1005mon',
    'Fullgen',
    'yasue_funayama0',
    'tanaka_shizuoka',
    'AlexSaito2019',
    'h_ototake',
    'ecoyuri',
    'araki_chiharu',
    'alphamath7',
    'ikedanob',
    'matsubarajin731',
    'masayo_tanabu',
    'takakonagae',
    'exngky289',
    'matsuikoji',
    'murata_kyonkyon',
    'izumi_akashi',
    'TEAM_Maehara',
    'Dougomi_Makiko',
    'shino7878shino',
    'kimura841',
    'jimihanako',
    'masanobu_ogura',
    'kitagamikeiro',
    'iwaxry_DPFP',
    'Natume_12',
    'nukoda1',
    'taro_co_taro',
    'eRYqMmQNb65cBxy',
    'nakanai_qilin',
    'T9xFAmhfwe7JA8A',
    'aoi_soma',
    'johnny_0419',
    'decadence_dolce',
    'tkzw21',
    'DPFPsupport',
}

members_list = []

for screen_name in user_list:
    print(screen_name)
    user = api.get_user(screen_name=screen_name)
    # print(user)
    user_info = [user.name, '@' + user.screen_name, user.followers_count]
    # print(user_info)
    if (user.statuses_count >= 10 ):
        members_list.append(user_info)

from operator import itemgetter

sorted_list = sorted(members_list, key=itemgetter(2), reverse=True)
print(*sorted_list, sep='\n')
# def follower_counts_func(acount):
#    followers_list = []
#    i = 0
#    cursor = -1
#    while cursor != 0:
#        auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
#        auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
#        api = tweepy.API(auth, wait_on_rate_limit=True)
#        itr = tweepy.Cursor(api.get_follower_ids, id=user_list[acount], cursor=cursor).pages()
#        try:
#            for follower_id in itr.next():
#                try:
#                    # print(follower_id)
#                    user = api.get_user(screen_name="tamakiyuichiro")
#                    user_info = [user.id_str, user.screen_name, user.name, user.followers_count,user.description]
#                    print(user)
#                    followers_list.append(user_info)
#                    i = i +1
#                 #    print(i, user_info)
#                except tweepy.error.TweepError as e:
#                    print(e.reason)
#        except ConnectionError as e:
#            print(e.reason)
#        cursor = itr.next_cursor
#    return followers_list
# followers_list = follower_counts_func(acount)
# print(followers_list.size)

# フォロワーの取得
# for user_id in user_ids:
#     # print('フォロワーを取得中...', end='')
#     itr = tweepy.Cursor(api.get_follower_ids, user_id=user_id, cursor=-1).items()
#     for follower_id in itr:
#         record = pd.Series([follower_id], index=follower_ids.columns)
#         follower_ids = follower_ids.append(record, ignore_index=True)
#     print(user_id)
#     print(follower_ids.size)
#     follower_ids = pd.DataFrame([], columns=cols)

# フォローしている人の取得
# print('フォローしている人を取得中...', end='')
# itr = tweepy.Cursor(api.get_friend_ids, user_id=user_id, cursor=-1).items() 
# for following_id in itr:
#     record = pd.Series([following_id], index=following_ids.columns)
#     following_ids = following_ids.append(record, ignore_index=True)
# print(' Done')

# oneside_follow = pd.DataFrame([], columns=['user_id', 'name', 'screen_name', 'description'])

# 一方的にフォローしている人を抽出
# print('一方的にフォローしている人を取得中...', end='')
# for following_id in following_ids['user_id']:
#     if following_id not in follower_ids['user_id'].values:
#         user = api.get_user(user_id=following_id)
#         record = pd.Series([user.id, user.name, user.screen_name, user.description], index=oneside_follow.columns)
#         oneside_follow = oneside_follow.append(record, ignore_index=True)
# print(' Done')

# removed_users = pd.DataFrame([], columns=['user_id', 'name', 'screen_name', 'description'])

# 一方的にフォローしている人をリムーブする
# print('以下のユーザーへのフォローを解除しました。')
# for i, user in oneside_follow.iterrows():
#     api.destroy_friendship(user_id=user.user_id)
#     removed_users = removed_users.append(user, ignore_index=True)
#     print('  アカウント名：' + user['name'] + ' / ユーザー名：' + user['screen_name'])

dir = os.path.dirname(__file__) + '/csv'
try:
    os.makedirs(dir)
except FileExistsError:
    pass
df = pd.DataFrame(sorted_list, columns=['name', 'screen_name', 'followers_count'])
df.to_csv(dir + '/sorted_users_' + datetime.datetime.now().strftime('%y%m%d%H%M%S') + '.csv')
# removed_users.to_csv(dir + '/removed_users_' + datetime.datetime.now().strftime('%y%m%d%H%M%S') + '.csv')